FROM ubuntu-armhf-toolchain
# There's needed file structure when installing dependecies with apt for boost like passwd
RUN cp /etc/passwd ${CHROOT_PATH}/etc/passwd
RUN cp /etc/group ${CHROOT_PATH}/etc/group
#
# WiringPi chroot install
#-------------------------
# chroot sh -c is the only way to execute chrooted cmd, you can't use multiple RUN once chrooted in Docker.
RUN chroot ${CHROOT_PATH} sh -c 'apt-get update && apt-get install libboost-all-dev libjsoncpp-dev libwebsocketpp-dev libssl-dev wget -y \
&& wget https://github.com/WiringPi/WiringPi/releases/download/2.61-1/wiringpi-2.61-1-${RASPI_ARCH}.deb --no-check-certificate \
&& dpkg -i wiringpi-2.61-1-${RASPI_ARCH}.deb'
#-------------------------
#
RUN apt-get install -y libboost-all-dev libjsoncpp-dev libwebsocketpp-dev libssl-dev